version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules
      - /var/www/vendor
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=news_web
      - DB_USERNAME=xt
      - DB_PASSWORD=adminxt32
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_KEY=base64:tQLS03Oul8z5yflI3yG5SMZ8Hm9eV7Bdb/YYpN3OTJ4=
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    command: tail -f /dev/null
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: news_web
      MYSQL_USER: xt
      MYSQL_PASSWORD: adminxt32
      MYSQL_ROOT_PASSWORD: adminxt32
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  dbdata:
